### ISSUE TITLE
Consider switching to sccache-action

### ISSUE THREAD

**Issue by fasterthanlime** [hapsoc/fluke#118]
cf. https://github.com/Mozilla-Actions/sccache-action

I'm not sure the cache action we're using for Win & macOS right now is doing its job well: on a PR, it took 2m30s to set itself up:

<img width="885" alt="image" src="https://github.com/hapsoc/fluke/assets/7998310/a7371523-c94f-45a8-966f-0212ff37dd18">

..then cargo check took 2m+ and cargo nextest 1.5m, for pretty simple changes. Maybe it just doesn't work well for PRs, but then why does it report the cache it found is a "full match"? And also, then why do we want it? PRs are how all the development happens.

**Comment by fasterthanlime** [comment]
Done in #126 and holy fuck, CI times for macOS went from 9 minutes to 1 minute:

![image](https://github.com/hapsoc/fluke/assets/7998310/0e5bcb27-5448-475c-910a-709979a2cb9e)

Windows is still slow-ish, gonna look into it.

**Comment by rgwood** [comment]
Hi there! A friend pointed me at this PR and I think I _might_ know what the issue was with your old caching setup.

I was noticing the same issue with Nushell's CI last year (new PRs were slow to build because of a `Swatinem/rust-cache` cache miss) and to fix it I added a new CI trigger to build and populate the cache on `main` after every merge. From [an old blog post](https://www.reillywood.com/blog/rust-faster-ci/):

> [GitHub Actions has slightly unintuitive behavior across PRs](https://stackoverflow.com/a/66632107). PR X is unable to see cache data from PR Y, but they can both see cache data from the base branch (usually main or master). This makes sense from an isolation perspective, but it’s not especially well-documented; I ended up adding [an extra CI trigger on main](https://github.com/nushell/nushell/blob/07893e01c15e7b4598141fb6d3876d5632b7ae0a/.github/workflows/ci.yml#L3-L5) just to fill caches properly.

This was a huge pain to figure out at the time, hopefully this info saves someone else pain in the future!

**Comment by fasterthanlime** [comment]
> I was noticing the same (?) issue

Thanks for the tip! This repository already has triggers for the main branch, pull requests AND merge group (needed to use the merge queue):

https://github.com/hapsoc/fluke/blob/468377b8095d58ad9857f5fa6ab8178e09779a6a/.github/workflows/test.yml#L3..L8
